version: '3.9'

services:
  # Spring Boot Application
  spring-app:
    image: pokemonapp
    ports:
      - "8081:8080"
    volumes:
      - ./application.properties:/app/application.properties
    networks:
      - pokemonapp-net
    depends_on:
      - mysql-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/pokemondb?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
      SERVER_PORT: 8080

  # MySQL Database
  mysql-db:
    image: mysql:8.0
    container_name: pokemon-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pokemondb
    ports:
      - "3308:3306"
    volumes:
    - mysql-data:/var/lib/mysql
    networks:
      - pokemonapp-net

volumes:
  mysql-data:
    driver: local

networks:
  pokemonapp-net: